
name: Push to Dockerhub
on:
  push:
    branches:
      - feature
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: 
          docker build -t node-app:latest -t node-app:${{ github.sha }} -f ./app/Dockerfile ./app 
          docker tag  node-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }}
  
          docker tag node-app:latest ${{ secrets.DOCKER_USERNAME }}/node-app:latest
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/node-app:latest
